// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/wordle": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/wordle" | "/*";
  };
  "./pages/Home.jsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/Wordle.jsx": {
    id: "pages/Wordle";
    page: "/wordle";
  };
  "catchall.tsx": {
    id: "catchall";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Home": typeof import("./src/./pages/Home.jsx");
  "pages/Wordle": typeof import("./src/./pages/Wordle.jsx");
  "catchall": typeof import("./src/catchall.tsx");
};